name: Hello World

on:
  push:
    branches: [ master ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World"
  date:
    runs-on: ubuntu-latest
    steps:
    - name: Prints date
      run: | 
        date
  directory_contents:
    runs-on: ubuntu-latest
    steps:
    - name: Prints directory contents
      run: | 
        ls
  build:
    runs-on: ubuntu-latest
    steps:
    - name: builds production software
      run: | 
        npm run build
  test:
    runs-on: ubuntu-latest
    steps:
    - name: runs all tests
      run: | 
        npm test
